In [1]:
import numpy as np

In [2]:
x = np.array([56,22,67,12,34,78,99,56])

In [3]:
x

array([56, 22, 67, 12, 34, 78, 99, 56])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.dtype

dtype('int32')

In [6]:
x.size

8

In [7]:
x[3]

12

In [8]:
y = np.array([56,22,67,12.56,34,78,99,56])

In [9]:
y

array([56.  , 22.  , 67.  , 12.56, 34.  , 78.  , 99.  , 56.  ])

In [10]:
y.dtype

dtype('float64')

In [11]:
y[1]

22.0

In [12]:
city = np.array([ 'कोलकाता' ,'पुणे' ,'केराला' ,'गुज्रत']) 

In [13]:
city

array(['कोलकाता', 'पुणे', 'केराला', 'गुज्रत'], dtype='<U7')

In [14]:
city.dtype

dtype('<U7')

In [15]:
city[3]

'गुज्रत'

In [16]:
type(city[3])

numpy.str_

In [17]:
z = np.array([[5,6,7], [9,8,7],[6,4,3],[7,0,5]])

In [18]:
z

array([[5, 6, 7],
       [9, 8, 7],
       [6, 4, 3],
       [7, 0, 5]])

In [19]:
z.shape

(4, 3)

In [20]:
z.dtype

dtype('int32')

In [23]:
z.max()

9

In [24]:
z.mean()

5.583333333333333